# OMNIX AI - Production Environment Configuration
# This file contains production-specific overrides

environment: production
stage: prod

# Frontend Configuration
frontend:
  s3_bucket: omnix-ai-frontend-animations-1755860292
  cloudfront_distribution_id: E2MCXLNXS3ZTKY  # Needs verification
  cloudfront_domain: d1vu6p9f5uc16.cloudfront.net
  build_command: "npm run build:production"
  build_env:
    VITE_API_BASE_URL: "https://4j4yb4b844.execute-api.eu-central-1.amazonaws.com/prod/v1"
    VITE_WEBSOCKET_URL: "wss://5oo31khrrj.execute-api.eu-central-1.amazonaws.com/prod"
    VITE_ENVIRONMENT: "production"
    VITE_DEBUG_MODE: "false"
    VITE_API_KEY: "omnix-api-key-production-2024"
    VITE_SENTRY_DSN: "${SENTRY_DSN}"
    
# Backend Configuration
backend:
  lambda_function_name: omnix-ai-backend-prod
  api_gateway_id: 4j4yb4b844
  api_gateway_stage: prod
  lambda_config:
    memory_size: 2048
    timeout: 60
    reserved_concurrent_executions: 100
    environment_variables:
      NODE_ENV: "production"
      LOG_LEVEL: "warn"
      CORS_ORIGINS: "https://d1vu6p9f5uc16.cloudfront.net,https://omnix-ai.com"
      JWT_SECRET_ARN: "arn:aws:secretsmanager:eu-central-1:631844602411:secret:omnix-jwt-prod"
      
# Database Configuration
database:
  dynamodb:
    tables_prefix: "omnix-ai-prod-"
    tables:
      - omnix-ai-prod-users
      - omnix-ai-prod-products
      - omnix-ai-prod-orders
      - omnix-ai-prod-inventory
      - omnix-ai-prod-sessions
    billing_mode: "PAY_PER_REQUEST"
    point_in_time_recovery: true
    encryption:
      enabled: true
      kms_key_id: "alias/omnix-ai-prod"
    backup:
      enabled: true
      schedule: "0 2 * * *"
      retention_days: 30
      
# High Availability Configuration
high_availability:
  multi_az: true
  auto_scaling:
    enabled: true
    min_capacity: 10
    max_capacity: 1000
    target_utilization: 70
    
# Deployment Configuration
deployment:
  strategy: "canary"
  canary_percentage: 10
  canary_duration: 600  # 10 minutes
  health_check_grace_period: 60
  rollback_on_failure: true
  approval_required: true
  
# Security
security:
  waf:
    enabled: true
    rules:
      - sql_injection_protection
      - xss_protection
      - rate_limiting
  api_throttling:
    rate_limit: 10000
    burst_limit: 5000
  ssl_certificate: "arn:aws:acm:us-east-1:631844602411:certificate/omnix-ai-prod"
  
# Monitoring
monitoring:
  cloudwatch:
    enabled: true
    enhanced_monitoring: true
    log_retention_days: 30
    metrics_enabled: true
    custom_metrics: true
  xray:
    enabled: true
    sampling_rate: 0.1
  alarms:
    error_rate_threshold: 1  # percent
    latency_p99_threshold: 3000  # ms
    concurrent_executions_threshold: 80  # percent
    4xx_rate_threshold: 5  # percent
    5xx_rate_threshold: 1  # percent
    
# Performance
performance:
  cdn_caching:
    enabled: true
    ttl:
      html: 0
      css: 31536000
      js: 31536000
      images: 31536000
  compression:
    enabled: true
    types:
      - text/html
      - text/css
      - application/javascript
      - application/json
      
# Disaster Recovery
disaster_recovery:
  backup_regions:
    - us-east-1
    - eu-west-1
  rpo: 3600  # Recovery Point Objective: 1 hour
  rto: 900   # Recovery Time Objective: 15 minutes
  
# Compliance
compliance:
  gdpr: true
  pci_dss: false
  hipaa: false
  soc2: true
  
# Cost Management
cost_optimization:
  s3_lifecycle_policies: true
  lambda_cost_allocation_tags:
    Environment: "production"
    Project: "omnix-ai"
    CostCenter: "engineering"
  cloudwatch_log_compression: true
  
# Notifications
notifications:
  pagerduty:
    enabled: true
    integration_key: "${PAGERDUTY_KEY}"
  slack:
    enabled: true
    channel: "#production-alerts"
    critical_channel: "#incidents"
  email:
    enabled: true
    addresses:
      - oncall@omnix-ai.com
      - engineering@omnix-ai.com
  sms:
    enabled: true
    numbers:
      - "+1234567890"