name: OMNIX AI - CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Frontend CI/CD
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/frontend
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './apps/frontend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint
        
      - name: Run unit tests
        run: npm run test:coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./apps/frontend/coverage
          flags: frontend
          
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Run E2E tests
        run: npm run test:e2e
        if: matrix.node-version == '20.x'
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '20.x'
        with:
          name: frontend-build
          path: ./apps/frontend/dist
          retention-days: 30
          
  # Backend CI/CD
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/backend
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './apps/backend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint || echo "Linting not configured yet"
        continue-on-error: true
        
      - name: Run unit tests
        run: npm run test || echo "Tests not configured yet"
        continue-on-error: true
        
      - name: Build TypeScript
        run: npm run build || npx tsc
        continue-on-error: true
        
      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '20.x'
        with:
          name: backend-build
          path: |
            ./apps/backend/dist
            ./apps/backend/deployment
          retention-days: 30

  # Security Scanning
  security:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run security audit (Frontend)
        run: |
          cd apps/frontend
          npm audit --audit-level moderate || exit 1
          
      - name: Run security audit (Backend) 
        run: |
          cd apps/backend
          npm audit --audit-level moderate || exit 1
          
      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high
        continue-on-error: true

  # Quality Gates
  quality:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install SonarQube Scanner
        run: |
          npm install -g sonar-scanner
          
      - name: Run SonarQube analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=omnix-ai \
            -Dsonar.sources=./apps \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

  # Staging Deployment
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [frontend, backend, security]
    if: github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./apps/frontend/dist
          
      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: ./apps/backend/dist
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Deploy to staging S3
        run: |
          aws s3 sync ./apps/frontend/dist s3://omnix-ai-staging-frontend --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_STAGING_ID }} --paths "/*"
          
      - name: Deploy Lambda functions
        run: |
          cd apps/backend/deployment
          zip -r lambda-deployment.zip .
          aws lambda update-function-code \
            --function-name omnix-ai-staging-api \
            --zip-file fileb://lambda-deployment.zip
            
      - name: Run staging health checks
        run: |
          sleep 30
          curl -f https://staging.omnix-ai.com/health || exit 1
          curl -f https://api-staging.omnix-ai.com/v1/health || exit 1

  # Production Deployment  
  deploy-production:
    runs-on: ubuntu-latest
    needs: [deploy-staging, quality]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./apps/frontend/dist
          
      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: ./apps/backend/dist
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: eu-central-1
          
      - name: Deploy to production S3
        run: |
          aws s3 sync ./apps/frontend/dist s3://omnix-ai-production-frontend --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_PROD_ID }} --paths "/*"
          
      - name: Deploy Lambda functions (Blue-Green)
        run: |
          cd apps/backend/deployment
          zip -r lambda-deployment.zip .
          
          # Deploy to blue environment first
          aws lambda update-function-code \
            --function-name omnix-ai-production-api-blue \
            --zip-file fileb://lambda-deployment.zip
            
          # Health check on blue
          sleep 30
          curl -f https://api-blue.omnix-ai.com/v1/health || exit 1
          
          # Switch traffic to blue (becomes green)
          aws lambda update-alias \
            --function-name omnix-ai-production-api \
            --name LIVE \
            --function-version $(aws lambda get-function --function-name omnix-ai-production-api-blue --query 'Configuration.Version' --output text)
            
      - name: Run production health checks
        run: |
          sleep 30
          curl -f https://omnix-ai.com/health || exit 1
          curl -f https://api.omnix-ai.com/v1/health || exit 1
          
      - name: Notify deployment success
        run: |
          echo "🚀 Production deployment successful!"
          echo "Frontend: https://omnix-ai.com"
          echo "API: https://api.omnix-ai.com/v1"

  # Monitoring and Alerts
  post-deploy:
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Setup monitoring
        run: |
          echo "Setting up post-deployment monitoring..."
          
      - name: Run synthetic tests
        run: |
          echo "Running synthetic user journey tests..."
          
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./apps/frontend/dist/**
            ./deployment-summary.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}